### ISSUE TITLE
Moving the camera too close (>-0.2) in the Z direction cuts off the lines

### ISSUE THREAD

**Issue by galoomba1** [Reinhardt-C/Reintope#2]
If this can't be fixed, would it be possible to add a zoom feature separate from the Z direction? High-dimensional objects appear very small currently

**Comment by Reinhardt-C** [comment]
I think I could add something that changes the FOV of the camera.

**Comment by Reinhardt-C** [comment]
Actually it looks like there might be a direct zoom property I can change.

**Comment by Reinhardt-C** [comment]
Alright, added a zoom slider locally :) It'll be pushed in the next update
