### ISSUE TITLE
Suggestion: change the ranges of sliders, and add a zoom slider

### ISSUE THREAD

**Issue by galoomba1** [Reinhardt-C/Reintope#3]
Here's how i'd do it:
Z: -20 - 0
W+: 0 - 20
Rotations: -1 - 1

The zoom slider would just zoom the final image because high-dimensional objects appear very small.

**Comment by Reinhardt-C** [comment]
Zoom slider added locally as per issue #2 
And sure, I'll make those changes :)

**Comment by Reinhardt-C** [comment]
I've made the changes to Z and W sliders as above, changed rotation to [-2, 2] as I feel like [-1, 1] was too restrictive. Will be pushed in the next update :)
